---
- name: Make sure that /var/appsdata dir exists
  file: path=/var/appsdata state=directory
- name: Copy merge_app_metadata.py script
  register: merge_script_updated
  copy:
    src: merge_app_metadata.py
    dest: /var/appsdata/merge_app_metadata.py
    force: true

- name: Setup cron job to run merge_app_metadata hourly
  cron:
    name: "merge app with its metadata"
    special_time: hourly
    job: "python /var/appsdata/merge_app_metadata.py"

- name: Execute merge_app_metadata script
  command: python /var/appsdata/merge_app_metadata.py
  when: merge_script_updated.changed
