---
# jupyterhub always runs image tagged as "aiidalab-docker-stack:latest"
- name: pull docker image from dockerhub
  become: true
  block:
    - name: pull docker image
      docker_image:
        name: aiidalab/aiidalab-docker-stack:{{ aiidalab_server_docker_stack }}
        source: pull
        force_source: true
      register: docker_pull
    - name: tag docker image
      command: docker tag aiidalab/aiidalab-docker-stack:{{ aiidalab_server_docker_stack }} aiidalab-docker-stack:latest
      changed_when: false
  when: not aiidalab_server_build_locally

- name: Build docker image locally
  tags: aiidalab_server_build_image
  block:
    - name: clone aiidalab-docker-stack repo
      git:
        repo: https://github.com/aiidalab/aiidalab-docker-stack.git
        dest: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
        accept_hostkey: true
        force: true
        version: "{{ aiidalab_server_docker_stack }}"
        recursive: false
      register: git_get
    - name: Build docker image (takes several minutes the first time)
      become: true
      docker_image:
        path: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
        name: aiidalab-docker-stack:latest
        force: true
        buildargs:
          NB_USER: "{{ aiidalab_server_user }}"
          NB_UID: "{{ aiidalab_server_uid }}"
          NB_GID: "{{ aiidalab_server_gid }}"
      when: do_build_image
  when: aiidalab_server_build_locally
