---
- name: pull docker image from dockerhub
  block:
    - name: pull docker image
      docker_image:
        name: aiidalab/aiidalab-docker-stack:{{ aiidalab_server_docker_stack }}
        tag: latest
        pull: true
      register: docker_pull
    - name: tag docker image
      shell: docker tag aiidalab/aiidalab-docker-stack:{{ aiidalab_server_docker_stack }} aiidalab-docker-stack:latest
      when: docker_pull.changed
  when: not aiidalab_server_build_locally

- name: Build docker image locally
  tags: aiidalab_server_build_image
  block:
    - name: clone aiidalab-docker-stack repo
      git:
        repo: https://github.com/aiidalab/aiidalab-docker-stack.git
        dest: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
        accept_hostkey: true
        force: true
        version: "{{ aiidalab_server_docker_stack }}"
        recursive: false
      register: git_get
    - name: Build docker image (takes several minutes the first time)
      docker_image:
        path: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
        name: aiidalab-docker-stack
        force: true
  when: aiidalab_server_build_locally
