---
# jupyterhub always runs image tagged as "aiidalab-docker-stack:latest"
- name: Pull the docker image from the DockerHub.
  become: true
  block:
    - name: Pull the docker image {{ aiidalab_server_image_name }}:{{ aiidalab_server_image_version }}.
      docker_image:
        name: "{{ aiidalab_server_image_name }}:{{ aiidalab_server_image_version }}"
        source: pull
        force_source: true
      register: docker_pull
    - name: Tag the docker image as 'aiidalab-docker-stack:latest'.
      command: docker tag {{ aiidalab_server_image_name }}:{{ aiidalab_server_image_version }} aiidalab-docker-stack:latest
      changed_when: false
  when: not aiidalab_server_build_locally

- name: Build the docker image locally.
  tags: aiidalab_server_build_image
  block:
    - name: Clone {{ aiidalab_server_image_git_repository }} repository. 
      git:
        repo: "{{ aiidalab_server_image_git_repository }}"
        dest: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
        accept_hostkey: true
        force: true
        version: "{{ aiidalab_server_image_version }}"
        recursive: false
      register: git_get
    - name: Build the docker image tagged as 'aiidalab-docker-stack:latest'. This might take several minutes.
      become: true
      docker_image:
        name: aiidalab-docker-stack
        tag: latest
        force_source: true
        source: build
        build:
          path: "{{ ansible_env.HOME }}/aiidalab-docker-stack"
          args:
            NB_USER: "{{ aiidalab_server_user }}"
            NB_UID: "{{ aiidalab_server_uid }}"
            NB_GID: "{{ aiidalab_server_gid }}"
  when: aiidalab_server_build_locally
