---
- name: Install JupyterHub apt dependencies
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - npm
      - nodejs
      - apache2
      - ntp
      - iotop
      - sysstat
      - htop

- name: Install JupyterHub npm dependencies
  npm:
    name: configurable-http-proxy
    # Note: version 4.0.1 did not work with node 4.2.6 on Ubuntu 16.04
    version: 4.2.1
    global: true

- name: Install JupyterHub pip3 dependencies
  pip:
    name: "{{ item.name }}"
    executable: pip3
    version: "{{ item.version }}"
  with_items:
    - name: pip
      version: 21.2.4
    - name: jupyterhub
      version: 1.5.0
    - name: jupyterhub-firstuseauthenticator
      version: 0.14.1
    - name: jupyter-client
      version: 6.1.12
    - name: dockerspawner
      version: 0.11.1
    - name: oauthenticator
      version: 0.13.0
    - name: dulwich
      version: 0.20.25
    - name: requests
      version: 2.26.0
    - name: python-jwt
      version: 3.3.0

- name: install recent docker python library
  pip:
    name: docker
    version: 4.2.0
    state: present
