---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  vars:
    - run_tests: true
    - cloud_platform: docker
    - aiidalab_server_docker_stack: 1.0b4-k8s

  roles:
    - role: "aiidalab.aiidalab_server"
