---
name: ci

on: [push, pull_request]

jobs:
  test-role:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run:  pip install -r requirements.txt

      # See https://github.com/geerlingguy/raspberry-pi-dramble/issues/166
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker

      - name: Launch molecule testing.
        run: molecule test
